# Generated by Django 5.2.17 on 2026-09-17 20:37

import django.db.models.deletion
import studio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nazwa')),
                ('width_cm', models.DecimalField(decimal_places=1, default=25, max_digits=5, verbose_name='szerokość (cm)')),
                ('height_cm', models.DecimalField(decimal_places=1, default=25, max_digits=5, verbose_name='wysokość (cm)')),
                ('base_price', models.DecimalField(decimal_places=2, default=249, max_digits=8, verbose_name='cena bazowa (zł)')),
                ('price_per_extra_spread', models.DecimalField(decimal_places=2, default=12, max_digits=7, verbose_name='dopłata za rozkładówkę powyżej 5')),
                ('is_active', models.BooleanField(default=True, verbose_name='dostępny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'format albumu',
                'verbose_name_plural': 'formaty albumów',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoverColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nazwa')),
                ('hex_code', models.CharField(default='#C39199', max_length=7, verbose_name='kolor (HEX)')),
                ('is_active', models.BooleanField(default=True, verbose_name='dostępny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'kolor okładki',
                'verbose_name_plural': 'kolory okładek',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoverMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nazwa')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='dopłata (zł)')),
                ('is_active', models.BooleanField(default=True, verbose_name='dostępny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'materiał okładki',
                'verbose_name_plural': 'materiały okładek',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Foil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='nazwa')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='dopłata (zł)')),
                ('is_active', models.BooleanField(default=True, verbose_name='dostępny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'tłoczenie',
                'verbose_name_plural': 'tłoczenia',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa projektu')),
                ('client_name', models.CharField(blank=True, max_length=120, verbose_name='klient')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail klienta')),
                ('client_phone', models.CharField(blank=True, max_length=40, verbose_name='telefon klienta')),
                ('cover_title', models.CharField(blank=True, max_length=60, verbose_name='tytuł na okładce')),
                ('cover_subtitle', models.CharField(blank=True, max_length=60, verbose_name='podpis na okładce')),
                ('spreads_count', models.PositiveIntegerField(default=10, verbose_name='liczba rozkładówek')),
                ('page_gap', models.PositiveIntegerField(default=10, verbose_name='odstęp między zdjęciami (px)')),
                ('page_padding', models.PositiveIntegerField(default=14, verbose_name='margines strony (px)')),
                ('page_bg', models.CharField(default='#FFFCF8', max_length=7, verbose_name='tło strony')),
                ('client_can_upload', models.BooleanField(default=True, verbose_name='klient może wgrywać własne zdjęcia')),
                ('client_editing_enabled', models.BooleanField(default=False, verbose_name='klient może projektować album')),
                ('status', models.CharField(choices=[('draft', 'szkic'), ('sent', 'wysłany do klienta'), ('in_progress', 'klient projektuje'), ('submitted', 'oddany do pracowni'), ('approved', 'zatwierdzony'), ('printing', 'w druku'), ('done', 'zrealizowany')], default='draft', max_length=20, verbose_name='status')),
                ('token', models.CharField(db_index=True, default=studio.models.new_token, max_length=64, unique=True, verbose_name='token linku')),
                ('note', models.TextField(blank=True, verbose_name='notatka pracowni')),
                ('client_note', models.TextField(blank=True, verbose_name='uwagi klienta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmodyfikowano')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='oddany przez klienta')),
                ('album_format', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='studio.albumformat', verbose_name='format')),
                ('cover_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='studio.covercolor', verbose_name='kolor okładki')),
                ('cover_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='studio.covermaterial', verbose_name='materiał okładki')),
                ('foil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='studio.foil', verbose_name='tłoczenie')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='fotograf')),
            ],
            options={
                'verbose_name': 'projekt',
                'verbose_name_plural': 'projekty',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'utworzono projekt'), ('photos', 'wgrano zdjęcia'), ('link', 'wysłano link klientowi'), ('client_save', 'klient zapisał układ'), ('submitted', 'klient oddał projekt'), ('status', 'zmiana statusu'), ('note', 'notatka')], max_length=20, verbose_name='zdarzenie')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='kiedy')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studio.project', verbose_name='projekt')),
            ],
            options={
                'verbose_name': 'zdarzenie',
                'verbose_name_plural': 'historia projektu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sesje/%Y/%m/', verbose_name='plik')),
                ('original_name', models.CharField(blank=True, max_length=200, verbose_name='nazwa pliku')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='ulubione')),
                ('uploaded_by_client', models.BooleanField(default=False, verbose_name='wgrane przez klienta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='wgrano')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studio.project', verbose_name='projekt')),
            ],
            options={
                'verbose_name': 'zdjęcie sesji',
                'verbose_name_plural': 'zdjęcia sesji',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='numer rozkładówki')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreads', to='studio.project', verbose_name='projekt')),
            ],
            options={
                'verbose_name': 'rozkładówka',
                'verbose_name_plural': 'rozkładówki',
                'ordering': ['index'],
                'unique_together': {('project', 'index')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'lewa'), ('R', 'prawa')], max_length=1, verbose_name='strona')),
                ('layout', models.CharField(choices=[('full', '1 duże'), ('two_v', '2 obok siebie'), ('two_h', '2 jedno nad drugim'), ('three', '1 + 2'), ('four', '4 w kratę'), ('six', '6 małych'), ('frame', '1 w ramce'), ('blank', 'puste')], default='two_v', max_length=20, verbose_name='układ')),
                ('caption', models.CharField(blank=True, max_length=120, verbose_name='podpis')),
                ('spread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='studio.spread', verbose_name='rozkładówka')),
            ],
            options={
                'verbose_name': 'strona',
                'verbose_name_plural': 'strony',
                'ordering': ['spread__index', 'side'],
                'unique_together': {('spread', 'side')},
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='pozycja')),
                ('zoom', models.FloatField(default=1.0, verbose_name='przybliżenie')),
                ('offset_x', models.FloatField(default=0, verbose_name='przesunięcie w poziomie (%)')),
                ('offset_y', models.FloatField(default=0, verbose_name='przesunięcie w pionie (%)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='studio.page', verbose_name='strona')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='studio.sessionphoto', verbose_name='zdjęcie')),
            ],
            options={
                'verbose_name': 'miejsce na zdjęcie',
                'verbose_name_plural': 'miejsca na zdjęcia',
                'ordering': ['index'],
                'unique_together': {('page', 'index')},
            },
        ),
    ]
