"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# klucz od Django, lokalnie może tak być. jak by to szło do internetu
# to trzeba zrobić nowy i trzymać go poza kodem (zmienna środowiskowa)
SECRET_KEY = 'django-insecure-i74s2v&jm9f!w$-7!ve2wpzz=8^77ky7i55%8g#6$a+@_d&q%3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# lokalnie True (pokazuje błędy), na serwerze musi być False

ALLOWED_HOSTS = ["*"]  # każdy adres, żeby dało się wejść z telefonu w domu


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'studio',  # moja aplikacja, reszta to rzeczy z Django
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # SQLite - baza w jednym pliku, nic nie trzeba instalować.
        # na jedną pracownię wystarczy, a jakby co to można zmienić na PostgreSQL
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pl'  # Django po polsku

TIME_ZONE = 'Europe/Amsterdam'  # czas lokalny w historii projektu

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- moje ustawienia ---
STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# tu lądują wgrane zdjęcia, folder jest w .gitignore żeby nie szły na GitHuba
LOGIN_URL = "/panel/login/"  # tu przenosi jak ktoś nie jest zalogowany
LOGIN_REDIRECT_URL = "/panel/"
LOGOUT_REDIRECT_URL = "/panel/login/"
# większe limity, bo zdjęcia z aparatu są duże i jest ich dużo naraz
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # max 100 MB na raz
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # większe niż 20 MB idą na dysk a nie do pamięci
DATA_UPLOAD_MAX_NUMBER_FILES = 400  # max 400 plików naraz
# z tych adresów przyjmuję formularze (ochrona CSRF)
CSRF_TRUSTED_ORIGINS = ["http://localhost:8000", "http://127.0.0.1:8000"]
STUDIO_NAME = "Pracownia Lamo"
STUDIO_EMAIL = "lamopracownia@gmail.com"
